apiVersion: apps/v1
kind: Deployment
metadata:
  name: ready-live-example
spec:
  selector:
    matchLabels:
      app: ready-live-example
  replicas: 1
  template:
    metadata:
      labels:
        app: ready-live-example
    spec:
      containers:
      - name: ready-live-test
        image: ready-live-example:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: https
          protocol: TCP
        env:
          - name: FAIL_READY
            value: "False"
          - name: FAIL_LIVE
            value: "False"
